### ISSUE TITLE
Properly Handle Comments and Invalid Keywords

### ISSUE THREAD

**Issue by mike-koch** [jandrewmc/SoftwareEngineering#3]
If we see `/*`, we should ignore all input until we see a `*/`.  Also, if we see any invalid keywords, we should throw an exception about invalid syntax.

**Comment by jandrewmc** [comment]
Invalid syntax is handled.  There is no specification and no example in any of the files he gave us related to comments in the code.  My only question is do we really NEED to allow for comments in the code.

**Comment by mike-koch** [comment]
If it's not in the specs, then I say we don't need to worry about it.  And if we're handling invalid syntax, then I say we are all good to go.
